### ISSUE TITLE
Add Second Dividend System

### ISSUE THREAD

**Issue by cakebank** [cakebank/cakebank_sol#5]
For current my code at
https://github.com/cakebank/cakebank_sol/blob/main/CAKEBANK.sol

The dividend system reward all holders above 200,000 token to be count as eligible holder.

I want to create dividend system two which reward all holders above 2,000,000 token to be count as eligible holder.

The system is same as the current dividend system, just another "pot" of rewards for the bigger holder.
The reward token can be set as "CAKE" default, and the sum 2,000,000 as default value.

**Comment by 0fatih** [comment]
Will you open a gitcoin bounty?
